openapi: 3.0.3
info:
  title: Todo API
  description: A simple todo list management API
  version: 1.0.0
servers:
  - url: http://localhost:3001
    description: Development server
paths:
  /todos:
    get:
      summary: Get all todos
      description: Retrieve a list of all todo items
      operationId: getAllTodos
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      summary: Create a new todo
      description: Create a new todo item
      operationId: createTodo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoRequest'
      responses:
        '201':
          description: Todo created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /todos/{id}:
    get:
      summary: Get a todo by ID
      description: Retrieve a specific todo item by its ID
      operationId: getTodoById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Todo found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    put:
      summary: Update a todo
      description: Update an existing todo item
      operationId: updateTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTodoRequest'
      responses:
        '200':
          description: Todo updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
        '404':
          description: Todo not found
    delete:
      summary: Delete a todo
      description: Delete a todo item by its ID
      operationId: deleteTodo
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Todo deleted successfully
        '404':
          description: Todo not found

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the todo
        title:
          type: string
          description: The todo title
        description:
          type: string
          description: Detailed description of the todo
        completed:
          type: boolean
          description: Whether the todo is completed
        created_at:
          type: string
          format: date-time
          description: When the todo was created
        updated_at:
          type: string
          format: date-time
          description: When the todo was last updated
      required:
        - id
        - title
        - completed
        - created_at
        - updated_at
    CreateTodoRequest:
      type: object
      properties:
        title:
          type: string
          description: The todo title
        description:
          type: string
          description: Detailed description of the todo
      required:
        - title
    UpdateTodoRequest:
      type: object
      properties:
        title:
          type: string
          description: The todo title
        description:
          type: string
          description: Detailed description of the todo
        completed:
          type: boolean
          description: Whether the todo is completed