// This file is auto-generated by @hey-api/openapi-ts

// Export types
export * from './types.gen';

// Export SDK methods
export * from './sdk.gen';

// Export client
export { createClient } from './client/client.gen';
export type {
  Client,
  Config,
  RequestOptions,
} from './client/types.gen';

// Export TanStack Query hooks
export * from './@tanstack/react-query.gen';

// Create default client instance
import { createClient } from './client/client.gen';
export const client = createClient();