# OpenAPI Tools Configuration for Google ADK
# 
# This configuration defines how OpenAPI specifications are converted 
# into ADK toolsets for your agents.
#
# Two integration methods are supported:
# - "direct": Uses Google ADK's OpenAPIToolset directly
# - "fastmcp": Uses FastMCP to create MCP servers, then connects via MCPToolset

default_integration_method: direct

# Directory paths (relative to backend/tools/)
openapi_specs_dir: openapi_specs

# Global authentication (can be overridden per API)
global_auth: {}

# FastMCP server settings
fastmcp_host: localhost
fastmcp_port_range: [9000, 9100]

# API Configurations
# Add your OpenAPI services here
apis:
  
  # Example 1: Swagger Petstore (URL-based, direct integration)
  petstore_demo:
    spec_source: "https://petstore3.swagger.io/api/v3/openapi.json"
    integration_method: direct
    operation_filter: 
      - "findPetsByStatus"
      - "addPet" 
      - "getPetById"
    tool_prefix: "pet_"
    enabled: false  # Set to true to enable
  
  # Example 2: JSONPlaceholder API (URL-based, FastMCP integration)
  jsonplaceholder_demo:
    spec_source: "https://jsonplaceholder.typicode.com/openapi.json"  # Note: This URL may not exist
    integration_method: fastmcp
    operation_filter:
      - "getPosts"
      - "createPost"
      - "getPost"
    tool_prefix: "blog_"
    cache_ttl: 3600
    enabled: false  # Set to true to enable
    
  # Example 3: Local OpenAPI spec file
  local_api_demo:
    spec_source: "todo_api.yaml"  # File in openapi_specs/ directory
    integration_method: direct
    operation_filter:
      - "getAllTodos"
      - "createTodo"
      - "getTodoById"
      - "updateTodo"
      - "deleteTodo"
    tool_prefix: "todo_"
    server_url: "http://localhost:3001"  # Override server URL
    enabled: false  # Set to true to enable

# Template for adding new APIs:
# 
# your_api_name:
#   spec_source: "https://api.example.com/openapi.json"  # OR "local_file.yaml"
#   integration_method: direct  # OR fastmcp
#   operation_filter:  # Optional - only include specific operations
#     - "operationId1"
#     - "operationId2"
#   tool_prefix: "myapi_"  # Optional - prefix for tool names
#   auth_scheme: "api_key"  # Optional - auth type
#   auth_credential: "MY_API_KEY_ENV_VAR"  # Optional - env var name
#   server_url: "https://custom-server.com"  # Optional - override server
#   cache_spec: true  # Optional - cache downloaded specs
#   cache_ttl: 3600  # Optional - cache time in seconds
#   enabled: true  # Set to false to disable